/* Ask-the-manual widget: fully client-side (static hosting friendly).
 *  - retrieval: BM25 over rag/index-{en,zh}.js, computed in the browser
 *  - answer: the browser calls the LLM endpoint the visitor typed into the settings (⚙); nothing is stored server-side
 */
(function () {
  var scope = (typeof __md_scope !== "undefined" && __md_scope.pathname) || "/";
  var isZh = /\/zh\/$/.test(scope);
  var root = isZh ? scope.replace(/zh\/$/, "") : scope;   // site root (index files live under <root>rag/)

  var T = isZh
    ? { btn: "AI 问答", title: "手册问答", ph: "问点什么,例如:怎么做过渡态优化?", send: "发送", stop: "停止",
        think: "思考中…", loading: "正在加载索引…", src: "参考页面", err: "出错了:", clear: "清空", gear: "设置",
        hint: "回答由大模型根据手册检索结果生成,请以原文为准。",
        ex: ["如何做过渡态优化?", "怎样设置内存和 CPU 核数?", "TD-DFT 计算激发态怎么写?"],
        nocfg: "还没有配置模型。请填写接口地址、模型名和密钥后保存。",
        net: "无法连接到该接口。常见原因:地址写错;接口没有开启跨域(CORS);页面是 https 而接口是 http(浏览器会拦截,localhost 除外)。",
        mixed: "当前页面是 https,浏览器不允许它访问 http 接口(localhost 除外)。请改用 https 地址,或在本机用 http://localhost 打开站点。",
        none: "手册中没有找到相关内容。",
        st: { type: "接口类型", base: "接口地址", model: "模型", key: "API 密钥", save: "保存", fetch: "获取模型列表", back: "返回",
              note: "配置只保存在本浏览器(localStorage,明文)。提问时由浏览器直接请求你填写的接口,不经过任何中转服务器。",
              none: "当前:尚未配置", cur: "当前:", saved: "已保存", fetching: "获取中…", got: " 个模型",
              types: { openai: "OpenAI 兼容", anthropic: "Anthropic", ollama: "Ollama" } },
        sys: "你是 Gaussian 16 用户手册的问答助手。只能依据用户消息中给出的手册摘录回答,不得使用摘录之外的知识补充。用中文简洁回答;每个要点或每句陈述末尾必须标注所依据的摘录编号,如 [1][3];没有出处的内容不要写。关键字、选项、Link 0 指令、输入示例必须与摘录原样一致,用代码格式。摘录没有涉及的部分,明确写“手册摘录中未提到”。",
        remind: "请只根据以上摘录回答,每个要点后必须带 [编号] 引用;摘录没有的内容不要写。", head: "=== 手册摘录 ===", q: "问题" }
    : { btn: "Ask AI", title: "Ask the manual", ph: "Ask something, e.g. how do I run a TS optimization?", send: "Send", stop: "Stop",
        think: "Thinking…", loading: "Loading index…", src: "Sources", err: "Error: ", clear: "Clear", gear: "Settings",
        hint: "Answers are generated by an LLM from retrieved manual passages; check the original text.",
        ex: ["How do I run a transition state optimization?", "How do I set memory and CPU cores?", "How do I compute excited states with TD-DFT?"],
        nocfg: "No model configured yet. Enter a base URL, model name and API key, then save.",
        net: "Cannot reach the endpoint. Usual causes: wrong URL; the endpoint does not allow cross-origin requests (CORS); the page is https but the endpoint is http (blocked by the browser, except localhost).",
        mixed: "This page is served over https and the browser will not let it call an http endpoint (except localhost). Use an https URL, or open the site via http://localhost.",
        none: "No relevant passage found in the manual.",
        st: { type: "Provider type", base: "Base URL", model: "Model", key: "API key", save: "Save", fetch: "Fetch model list", back: "Back",
              note: "Saved only in this browser (localStorage, plain text). Questions go straight from your browser to the endpoint you enter; there is no relay server.",
              none: "Current: not configured", cur: "Current: ", saved: "Saved", fetching: "Fetching…", got: " models",
              types: { openai: "OpenAI-compatible", anthropic: "Anthropic", ollama: "Ollama" } },
        sys: "You are the Q&A assistant for the Gaussian 16 Users Reference. Answer ONLY from the manual excerpts in the user message; add nothing from outside knowledge. Be concise. Every point or statement must end with the number(s) of the excerpt it relies on, e.g. [1][3]; do not write anything that has no source. Keywords, options, Link 0 commands and inputs must match the excerpts exactly, in code format. For anything the excerpts do not cover, say \"not mentioned in the excerpts\".",
        remind: "Answer only from the excerpts above; every point must carry a [number] citation; do not add anything the excerpts lack.", head: "=== Manual excerpts ===", q: "Question" };

  var history = [], busy = null, STORE = "ask-chat", LS = "ask-llm";
  var PH = { openai: "https://api.openai.com/v1", anthropic: "https://api.anthropic.com", ollama: "http://localhost:11434" };

  function el(tag, cls, html) { var e = document.createElement(tag); if (cls) e.className = cls; if (html != null) e.innerHTML = html; return e; }
  function esc(s) { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
  function loadCfg() { try { return JSON.parse(localStorage.getItem(LS) || "{}"); } catch (e) { return {}; } }

  /* ---------- retrieval (mirror of rag/index.py) ---------- */
  var STOP = {};
  ("如何 怎么 怎样 什么 为什么 是否 可以 能否 哪些 一个 我想 请问 应该 需要 如 何 怎 样 吗 的 了 是 在 和 与 做 要 用 个 么 请 我 有 还 能 会 都 就 也 对 把 被 到 从 上 下 中 里 吧 呢 啊 how do i does the a an to of in on for is are what which can should please")
    .split(" ").forEach(function (w) { STOP[w] = 1; });

  // natural-language words -> the keyword names the manual actually uses (Opt=TS, %Mem, Freq, SCRF, ...)
  var SYN = {
    optimization: "opt", optimize: "opt", optimise: "opt", optimizing: "opt", geometry: "geom opt", transition: "ts qst2 qst3",
    memory: "mem", frequency: "freq", frequencies: "freq", vibrational: "freq", excited: "td cis", tddft: "td",
    solvent: "scrf", solvation: "scrf", basis: "gen", functional: "dft", checkpoint: "chk", parallel: "nprocshared cpu",
    cores: "nprocshared cpu", processors: "nprocshared cpu", threads: "nprocshared cpu",
    "过渡": "ts qst2 qst3", "优化": "opt", "内存": "mem", "频率": "freq", "振动": "freq", "激发": "td cis", "溶剂": "scrf",
    "基组": "gen", "泛函": "dft", "检查点": "chk", "并行": "nprocshared cpu", "核数": "nprocshared cpu", "线程": "nprocshared cpu"
  };

  function tokenize(text) {
    var t = text.toLowerCase(), toks = t.match(/[a-z0-9]+/g) || [];
    (t.match(/[一-鿿]+/g) || []).forEach(function (run) {
      for (var i = 0; i < run.length; i++) toks.push(run[i]);
      for (var j = 0; j < run.length - 1; j++) toks.push(run.slice(j, j + 2));
    });
    return toks;
  }
  var indexes = {};
  function loadIndex(lang) {
    if (!indexes[lang]) {
      indexes[lang] = new Promise(function (resolve, reject) {
        if (window.ASK_IDX && window.ASK_IDX[lang]) return resolve(window.ASK_IDX[lang]);
        var sc = document.createElement("script");   // a <script> works over http(s) and file://, unlike fetch()
        sc.src = root + "rag/index-" + lang + ".js";
        sc.onload = function () { window.ASK_IDX && window.ASK_IDX[lang] ? resolve(window.ASK_IDX[lang]) : reject(new Error("index empty")); };
        sc.onerror = function () { delete indexes[lang]; reject(new Error("cannot load " + sc.src)); };
        document.head.appendChild(sc);
      });
    }
    return indexes[lang];
  }
  function search(ix, query, k) {
    var n = ix.chunks.length, k1 = 1.5, b = 0.75, sc = {}, qf = {};
    tokenize(query).forEach(function (w) { if (!STOP[w]) qf[w] = (qf[w] || 0) + 1; });
    Object.keys(qf).forEach(function (w) {
      if (SYN[w]) SYN[w].split(" ").forEach(function (t) { qf[t] = (qf[t] || 0) + 1; });
    });
    Object.keys(qf).forEach(function (w) {
      var p = ix.post[w]; if (!p) return;
      var d = p.length / 2, idf = Math.log(1 + (n - d + 0.5) / (d + 0.5));
      for (var j = 0; j < p.length; j += 2) {
        var i = p[j], f = p[j + 1];
        sc[i] = (sc[i] || 0) + idf * f * (k1 + 1) / (f + k1 * (1 - b + b * ix.lens[i] / ix.avg)) * (1 + 0.1 * (qf[w] - 1));
      }
    });
    return Object.keys(sc).map(function (i) { return [+i, sc[i]]; }).sort(function (a, c) { return c[1] - a[1]; }).slice(0, k);
  }
  function retrieve(question) {
    var lang = /[一-鿿]/.test(question) ? "zh" : "en", q = question;
    var prev = history.filter(function (m) { return m.role === "user"; }).slice(-1)[0];
    if (prev && question.length < 25) q = prev.content + " " + question;   // short follow-up
    return loadIndex(lang).then(function (ix) {
      var hits = [], perFile = {}, used = 0, top = null;
      var ranked = search(ix, q, 40);
      for (var r = 0; r < ranked.length; r++) {
        var c = ix.chunks[ranked[r][0]], s = ranked[r][1];
        if (top === null) top = s;
        if (s < 0.55 * top) break;
        if ((perFile[c.f] || 0) >= 3) continue;
        if (used + c.x.length > 11000 && hits.length) continue;
        perFile[c.f] = (perFile[c.f] || 0) + 1; hits.push(c); used += c.x.length;
        if (hits.length >= 8) break;
      }
      return { lang: lang, hits: hits };
    });
  }
  function buildMessages(question, hits) {
    var ctx = hits.map(function (c, i) { return "[" + (i + 1) + "] " + c.t + " (" + c.f + ")\n" + c.x; }).join("\n\n");
    var msgs = [{ role: "system", content: T.sys }];
    history.slice(-6).forEach(function (m) { msgs.push({ role: m.role, content: m.content.slice(0, 2000) }); });
    msgs.push({ role: "user", content: T.head + "\n" + ctx + "\n\n" + T.q + ": " + question + "\n\n" + T.remind });
    return msgs;
  }

  /* ---------- LLM clients (browser -> endpoint) ---------- */
  function readStream(resp, onLine) {
    var rd = resp.body.getReader(), dec = new TextDecoder(), buf = "";
    function pump() {
      return rd.read().then(function (res) {
        if (res.done) { if (buf.trim()) onLine(buf); return; }
        buf += dec.decode(res.value, { stream: true });
        var lines = buf.split("\n"); buf = lines.pop();
        lines.forEach(onLine);
        return pump();
      });
    }
    return pump();
  }
  function checkOk(r) {
    if (r.ok) return r;
    return r.text().then(function (t) { throw new Error("HTTP " + r.status + " " + t.slice(0, 200)); });
  }
  function streamLLM(cfg, msgs, signal, onToken, onThink) {
    var base = cfg.base.replace(/\/+$/, "");
    if (cfg.type === "anthropic") {
      var url = base + (/\/v1$/.test(base) ? "/messages" : "/v1/messages");
      return fetch(url, {
        method: "POST", signal: signal,
        headers: { "Content-Type": "application/json", "x-api-key": cfg.key, "anthropic-version": "2023-06-01", "anthropic-dangerous-direct-browser-access": "true" },
        body: JSON.stringify({ model: cfg.model, max_tokens: 4000, temperature: 0.1, stream: true, system: msgs[0].content, messages: msgs.slice(1) })
      }).then(checkOk).then(function (r) {
        return readStream(r, function (line) {
          if (line.indexOf("data:") !== 0) return;
          try { var d = JSON.parse(line.slice(5)); if (d.type === "content_block_delta" && d.delta && d.delta.text) onToken(d.delta.text); } catch (e) {}
        });
      });
    }
    if (cfg.type === "ollama") {
      return fetch(base + "/api/chat", {
        method: "POST", signal: signal, headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ model: cfg.model, messages: msgs, stream: true, options: { temperature: 0.1, num_ctx: 16384 } })
      }).then(checkOk).then(function (r) {
        return readStream(r, function (line) {
          if (!line.trim()) return;
          try { var m = JSON.parse(line).message || {}; if (m.thinking) onThink(); if (m.content) onToken(m.content); } catch (e) {}
        });
      });
    }
    var headers = { "Content-Type": "application/json" };
    if (cfg.key) headers.Authorization = "Bearer " + cfg.key;
    return fetch(base + "/chat/completions", {
      method: "POST", signal: signal, headers: headers,
      body: JSON.stringify({ model: cfg.model, messages: msgs, stream: true, temperature: 0.1, max_tokens: 8000 })
    }).then(checkOk).then(function (r) {
      return readStream(r, function (line) {
        if (line.indexOf("data:") !== 0) return;
        var p = line.slice(5).trim(); if (!p || p === "[DONE]") return;
        try {
          var ch = ((JSON.parse(p).choices || [{}])[0] || {}).delta || {};
          if (ch.reasoning_content || ch.reasoning) onThink();
          if (ch.content) onToken(ch.content);
        } catch (e) {}
      });
    });
  }
  function listModels(cfg) {
    var base = cfg.base.replace(/\/+$/, "");
    if (cfg.type === "ollama") return fetch(base + "/api/tags").then(checkOk).then(function (r) { return r.json(); }).then(function (d) { return (d.models || []).map(function (m) { return m.name; }); });
    var h = cfg.type === "anthropic"
      ? { "x-api-key": cfg.key, "anthropic-version": "2023-06-01", "anthropic-dangerous-direct-browser-access": "true" }
      : (cfg.key ? { Authorization: "Bearer " + cfg.key } : {});
    var url = base + (cfg.type === "anthropic" && !/\/v1$/.test(base) ? "/v1/models" : "/models");
    return fetch(url, { headers: h }).then(checkOk).then(function (r) { return r.json(); }).then(function (d) { return (d.data || []).map(function (m) { return m.id; }); });
  }
  function mixedBlocked(base) {
    return location.protocol === "https:" && /^http:\/\//i.test(base) && !/^http:\/\/(localhost|127\.0\.0\.1|\[::1\])/i.test(base);
  }

  /* ---------- rendering ---------- */
  function render(text, sources) {
    var parts = text.split(/```/), out = "";
    parts.forEach(function (p, i) {
      if (i % 2) { out += "<pre><code>" + esc(p.replace(/^[^\n]*\n/, "")) + "</code></pre>"; return; }
      var h = esc(p)
        .replace(/`([^`\n]+)`/g, "<code>$1</code>")
        .replace(/\*\*([^*\n]+)\*\*/g, "<strong>$1</strong>")
        .replace(/\[(\d+)\]/g, function (m, n) {
          var s = sources && sources[+n - 1];
          return s ? '<a class="ask-cite" href="' + root + s.url + '" title="' + esc(s.title) + '">' + n + "</a>" : m;
        });
      var lines = h.split("\n"), html = "", inList = false;
      lines.forEach(function (l) {
        var li = l.match(/^\s*(?:[-*]|\d+\.)\s+(.*)$/);
        if (li) { if (!inList) { html += "<ul>"; inList = true; } html += "<li>" + li[1] + "</li>"; return; }
        if (inList) { html += "</ul>"; inList = false; }
        var hd = l.match(/^#{1,6}\s+(.*)$/);
        html += hd ? "<p><strong>" + hd[1] + "</strong></p>" : (l.trim() ? "<p>" + l + "</p>" : "");
      });
      if (inList) html += "</ul>";
      out += html;
    });
    return out;
  }

  /* ---------- UI ---------- */
  function build() {
    var fab = el("button", "ask-fab", "💬 " + T.btn);
    var panel = el("div", "ask-panel"); panel.hidden = true;
    var head = el("div", "ask-head", "<span>" + T.title + "</span>");
    var gear = el("button", "ask-link", "⚙"); gear.title = T.gear;
    var clear = el("button", "ask-link", T.clear), close = el("button", "ask-link", "✕");
    head.appendChild(gear); head.appendChild(clear); head.appendChild(close);
    var set = el("div", "ask-set"); set.hidden = true;
    var log = el("div", "ask-log");
    var hint = el("div", "ask-hint", T.hint);
    var form = el("form", "ask-form");
    var input = el("textarea"); input.rows = 2; input.placeholder = T.ph;
    var send = el("button", "ask-send", T.send); send.type = "submit";
    form.appendChild(input); form.appendChild(send);
    panel.appendChild(head); panel.appendChild(set); panel.appendChild(log); panel.appendChild(hint); panel.appendChild(form);
    document.body.appendChild(fab); document.body.appendChild(panel);

    /* settings view */
    var typeOpts = Object.keys(T.st.types).map(function (k) { return '<option value="' + k + '">' + T.st.types[k] + "</option>"; }).join("");
    set.innerHTML =
      "<label>" + T.st.type + '<select class="f-type">' + typeOpts + "</select></label>" +
      "<label>" + T.st.base + '<input class="f-base" autocomplete="off" spellcheck="false"></label>' +
      "<label>" + T.st.model + '<input class="f-model" list="ask-models" autocomplete="off" spellcheck="false"><datalist id="ask-models"></datalist></label>' +
      '<div><button type="button" class="ask-mini f-fetch">' + T.st.fetch + '</button> <span class="f-msg"></span></div>' +
      "<label>" + T.st.key + '<input class="f-key" type="password" autocomplete="off"></label>' +
      '<div class="ask-note">' + T.st.note + '</div><div class="ask-cur"></div>' +
      '<div class="ask-row"><button type="button" class="ask-send f-save">' + T.st.save + '</button><button type="button" class="ask-mini f-back">' + T.st.back + "</button></div>";
    var f = function (c) { return set.querySelector(".f-" + c); };
    function showCur() {
      var c = loadCfg();
      set.querySelector(".ask-cur").textContent = (c.base && c.model) ? T.st.cur + c.model + " @ " + c.base : T.st.none;
    }
    function fill() {
      var c = loadCfg();
      f("type").value = c.type || "openai"; f("base").value = c.base || ""; f("model").value = c.model || ""; f("key").value = c.key || "";
      f("base").placeholder = PH[f("type").value]; f("msg").textContent = ""; showCur();
    }
    function formCfg() { return { type: f("type").value, base: f("base").value.trim(), model: f("model").value.trim(), key: f("key").value.trim() }; }
    f("type").onchange = function () { f("base").placeholder = PH[f("type").value]; };
    f("fetch").onclick = function () {
      var c = formCfg(), m = f("msg");
      if (!c.base) { m.textContent = T.st.base + "?"; return; }
      if (mixedBlocked(c.base)) { m.textContent = T.mixed; return; }
      m.textContent = T.st.fetching;
      listModels(c).then(function (ids) {
        set.querySelector("#ask-models").innerHTML = ids.map(function (id) { return '<option value="' + esc(id) + '">'; }).join("");
        m.textContent = ids.length + T.st.got;
      }).catch(function (e) { m.textContent = e instanceof TypeError ? T.net : String(e.message || e); });
    };
    function toggleSettings(on) { set.hidden = !on; log.hidden = form.hidden = hint.hidden = on; if (on) fill(); }
    gear.onclick = function () { toggleSettings(set.hidden); };
    f("back").onclick = function () { toggleSettings(false); };
    f("save").onclick = function () {
      var c = formCfg();
      try { if (c.base || c.model || c.key) localStorage.setItem(LS, JSON.stringify(c)); else localStorage.removeItem(LS); } catch (e) {}
      f("msg").textContent = T.st.saved; showCur();
    };

    /* chat view */
    function welcome() {
      log.innerHTML = "";
      var w = el("div", "ask-msg bot");
      T.ex.forEach(function (q) {
        var b = el("button", "ask-chip", esc(q)); b.type = "button";
        b.onclick = function () { input.value = q; form.requestSubmit(); };
        w.appendChild(b);
      });
      log.appendChild(w);
    }
    function save() {
      try { sessionStorage.setItem(STORE, JSON.stringify({ open: !panel.hidden, history: history, log: history.length ? log.innerHTML : "" })); } catch (e) {}
    }
    welcome();
    try {
      var st = JSON.parse(sessionStorage.getItem(STORE) || "null");
      if (st && st.history && st.history.length && st.log) {
        history = st.history; log.innerHTML = st.log; log.scrollTop = log.scrollHeight;
        if (st.open) { panel.hidden = false; fab.hidden = true; }
      } else if (st && st.open) { panel.hidden = false; fab.hidden = true; }
    } catch (e) {}

    fab.onclick = function () { panel.hidden = false; fab.hidden = true; input.focus(); save(); };
    close.onclick = function () { panel.hidden = true; fab.hidden = false; save(); };
    clear.onclick = function () { if (busy) busy.abort(); history = []; welcome(); save(); };
    input.addEventListener("keydown", function (e) { if (e.key === "Enter" && !e.shiftKey && !e.isComposing) { e.preventDefault(); form.requestSubmit(); } });

    form.onsubmit = function (e) {
      e.preventDefault();
      if (busy) { busy.abort(); return; }
      var q = input.value.trim(); if (!q) return;
      var cfg = loadCfg();
      if (!cfg.base || !cfg.model) { toggleSettings(true); f("msg").textContent = T.nocfg; return; }
      input.value = "";
      if (history.length === 0) log.innerHTML = "";
      log.appendChild(el("div", "ask-msg user", esc(q)));
      var bot = el("div", "ask-msg bot", '<span class="ask-dim">' + T.loading + "</span>");
      log.appendChild(bot); log.scrollTop = log.scrollHeight;
      var text = "", sources = [], ctl = new AbortController(); busy = ctl; send.textContent = T.stop;

      function finish() {
        busy = null; send.textContent = T.send;
        if (text) history.push({ role: "user", content: q }, { role: "assistant", content: text });
        save();
      }
      function showSources() {
        var seen = {}, lis = "";
        sources.forEach(function (s) {
          if (text.indexOf("[" + s.n + "]") < 0 || seen[s.url + s.title]) return;
          seen[s.url + s.title] = 1;
          lis += '<a href="' + root + s.url + '">[' + s.n + "] " + esc(s.title) + "</a>";
        });
        if (!lis) return;
        var box = bot.querySelector(".ask-src");
        if (!box) { box = el("details", "ask-src"); bot.appendChild(box); }
        box.innerHTML = "<summary>" + T.src + "</summary>" + lis;
      }
      function fail(err) {
        if (err && err.name === "AbortError") { finish(); return; }
        var msg = err instanceof TypeError ? T.net : T.err + esc(String((err && err.message) || err));
        bot.innerHTML = (text ? render(text, sources) : "") + '<p class="ask-err">' + msg.replace(cfg.key || "\u0000", "***") + "</p>";
        finish();
      }

      if (mixedBlocked(cfg.base)) { bot.innerHTML = '<p class="ask-err">' + T.mixed + "</p>"; finish(); return; }
      retrieve(q).then(function (r) {
        sources = r.hits.map(function (c, i) { return { n: i + 1, title: c.t, url: c.u }; });
        if (!r.hits.length) { text = T.none; bot.innerHTML = "<p>" + T.none + "</p>"; return; }
        bot.innerHTML = '<span class="ask-dim">' + T.think + "</span>";
        return streamLLM(cfg, buildMessages(q, r.hits), ctl.signal,
          function (tok) { text += tok; bot.innerHTML = render(text, sources); showSources(); log.scrollTop = log.scrollHeight; },
          function () {}
        );
      }).then(finish, fail);
    };
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", build); else build();
})();
